#!/usr/bin/env python3

# GOV: Grep and Open with Vim
# Author : Ji-Hun Kim(jihuun.k@gmail.com)
# v 0.2.0

import os
import sys

tmp_outfile='.tmp_gov_result.txt'

result = list()

def grep_to_file():
    arg=sys.argv[1]
    cmd='grep -nr \"%s\" ./* > %s' %(arg, tmp_outfile)
    os.system(cmd)

def save_to_list():
    f = open(tmp_outfile, 'r')
    i = 0
    while True:
        line = f.readline()
        if not line:
            break
        line_info = line.split(':')
        result.append(line_info)
        #print('%d'%i, result[i])
        i = i + 1
    f.close()

def print_results():
    for i in range(len(result)):
        result[i][2] = result[i][2].replace('\t','')
        result[i][2] = result[i][2].replace('\n','')
        print('%d: %-35s: %s'%(i, result[i][0], result[i][2]))
    return

def open_vim():
    print('select number to open:')
    getnum=int(input())
    vim_cmd='vim %s +%s'%(result[getnum][0], result[getnum][1])
    os.system(vim_cmd)

def main():
    grep_to_file()
    save_to_list()
    print_results()
    open_vim()
    os.remove(tmp_outfile)

if __name__ == '__main__':
    main()
